### ISSUE TITLE
Client might not be able to detect a response

### ISSUE THREAD

**Issue by sigve10** [sigve10/socket-sandbox#14]
Due to how clients have no obligation to wait for a response from the server, it is impossible to know when a response has actually been sent to the client. Additionally, due to broadcasts, it is impossible to wait for a response without having changed the protocol.

Since this falls on the user to implement a protocol to distinguish the messages, we should at the very least provide a method to wait for a server message, and leave it up to the user to be able to distinguish between messages and handle potential issues (such as never getting a response). Optionally, we can leave it up to the user to wait for a message in a while loop so they have better control over the waiting process.

**Comment by sigve10** [comment]
A solution to this is changing the client to an observer pattern, and firing listeners whenever a message is received.

**Comment by bratseth1** [comment]
Implemented the observer pattern as suggested and it's now merged into the main branch. This pattern addresses the issue of the client not being able to detect a server response by notifying all registered listeners whenever a message is received. The new approach provides the client with a more robust and responsive way to handle incoming messages and allows for better control over the message handling process.
